name: dbt CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  dbt:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
    steps:
      - name: Debug env
        run: |
          echo "ACCOUNT: $SNOWFLAKE_ACCOUNT"
          
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dbt
        run: |
          pip install dbt-snowflake

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt

          cat > ~/.dbt/profiles.yml <<EOF
          elt_project:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: ${SNOWFLAKE_ACCOUNT}
                user: ${SNOWFLAKE_USER}
                password: ${SNOWFLAKE_PASSWORD}
                role: ${SNOWFLAKE_ROLE}
                database: ${SNOWFLAKE_DATABASE}
                warehouse: ${SNOWFLAKE_WAREHOUSE}
                schema: staging
                threads: 4
          EOF

      - name: dbt debug
        run: dbt debug
        working-directory: ./elt_project

      - name: dbt deps
        run: dbt deps
        working-directory: ./elt_project

      - name: dbt build
        run: dbt build
        working-directory: ./elt_project